#cloud-config
ssh_pwauth: yes
chpasswd:
  expire: false
  list:
    - root:${root_password}
runcmd:
  - sed -i -e '/^#PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart sshd.service
